# Generated by Django 5.0.7 on 2024-08-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapi_app', '0002_remove_person_age_remove_person_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
